a=int(input("enter 1st value"))
b=int(input("enter 2nd value"))
c=a+b              #(+)addition operator
print("add=",c)     
c=a-b              #(-)minus operator
print("sub=",c)
c=a*b              #(*)multipication operator
print("mul=",c)
c=a/b              #(/)division operator
print("div=",c)
c=a%b              #(%)modulo opertor[returns the value of remainder after division]
print("mod=",c)
