name=input("enter yor name")
print("name:",name)
roll_no=int(input("enter roll_no: "))
print("roll_no:",roll_no)
marks=float(input("enter marks: "))
print("marks:",marks) 

name=input("enter yor name")
print("name:",name)
print(type(name))
roll_no=int(input("enter roll_no: "))
print("roll_no:",roll_no)
print(type(roll_no))
marks=float(input("enter marks: "))
print("marks:",marks)
print(type(marks)) 